### ISSUE TITLE
How do I add css file to content.js?

### ISSUE THREAD

**Issue by harshamobiux** [hindmost/cra-rich-chrome-ext-example#1]
Normally I would include the css file in the manifest.json like below,
"content_scripts": [{
    "js": [ "content.js" ],
    "css": ["content.css"],
    "matches": [
      "<all_urls>"
    ]
  }]

But, it does not seem to work in react chrome extension. Any ideas?

**Comment by hindmost** [comment]
Normally you would do the same with Create React App if you read [their docs](https://create-react-app.dev/docs/getting-started/) attentively.
Just put your css file into the [public](https://create-react-app.dev/docs/using-the-public-folder) folder (`"public/content.css"`) and it will be available as `"content.css"` in the build folder.

BTW, you could star this repo, if it was useful for you.
